version: '3.4'
services:
  webfrontend: 
   image: ${DOCKER_REGISTRY-}webfrontend
   ports:
     - "8001:80"
   build:
     context: ..
     dockerfile: WebFrontEnd/Dockerfile
     
  mywebapi:
    image: ${DOCKER_REGISTRY-}mywebapi
    ports:
      - "8000:80"
    build:
      context: ..
      dockerfile: MyWebAPI/Dockerfile
